name: 'Update schedule'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'
permissions:
  contents: write
jobs:
  push:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
    steps:
      - name: Set branch name
        run: echo "BRANCH_NAME=${BRANCH_NAME:-master}" >> $GITHUB_ENV
        env:
          BRANCH_NAME: ${{ github.repository_owner == 'Guovin' && 'gd' || 'master' }}
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Install pipenv
        run: |
          pip3 install --user pipenv
          export PATH="$PATH:/home/runner/.local/bin"
      - name: Install dependecies
        run: |
          export PATH="$PATH:/home/runner/.local/bin"
          pipenv --python 3.14 && pipenv install --deploy
      - name: Update
        run: |
          export PATH="$PATH:/home/runner/.local/bin"
          pipenv run dev
      - name: Commit and push if changed
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Github Action Auto Updated"
            git push --force
          fi
