名称: “更新计划”


  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  push:
运行于: ${{matrix.操作系统}}
策略:
矩阵:
操作系统: [ 'ubuntu-latest' ]
步骤:
      - 名称: 设置分支名称
        id: vars
运行: echo"BRANCH_NAME=${{ github.repository_owner == 'Guovin' && 'gd' || 'master' }}">> $GITHUB_ENV
      - 用途: actions/checkout@v6
:
${{env.BRANCH_NAME}
      - 名称: 使用 setup-python 3.14 运行
用途: actions/setup-python@v6
与:
python版本: '3.14'
更新环境: true
缓存: 'pipenv'
      - 名称: 安装FFmpeg
运行: sudo apt-get update && sudo apt-get install -y ffmpeg
      - 名称: 安装 pipenv
运行: pip3 install --user pipenv
      - 名称: 安装依赖项
运行: Pipenv --python 3.14 && Pipenv install --deploy
      - 名称: 更新
运行: pipenv 运行 dev
      - 名称: 如有更改则提交并推送
运行: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
如果 ! git diff --staged --quiet; 则
git commit -m "Github Action 自动更新"
            git push --force
          fi
